# Generated by Django 5.2.5 on 2025-09-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularityRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('EBOOK', 'Version ebook'), ('PLUS', 'Version améliorée')], default='EBOOK', max_length=10)),
                ('irregularity', models.TextField(help_text='Irrégularité constatée')),
                ('reference', models.CharField(blank=True, help_text='Référence juridique/texte', max_length=255)),
                ('actors', models.CharField(blank=True, help_text='Acteurs concernés', max_length=255)),
                ('dispositions', models.TextField(help_text='Dispositions pratiques/recommandations')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregularity_rows', to='store.product')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
