# Generated by Django 5.2.5 on 2025-09-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_irregularityrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irregularityrow',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irregularity_rows', to='store.product'),
        ),
        migrations.CreateModel(
            name='IrregularityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('group', models.CharField(choices=[('FUNCTION', 'Fonction'), ('STRUCTURE', 'Structure')], default='STRUCTURE', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_categories', to='store.product')),
            ],
            options={
                'ordering': ('order', 'title'),
                'unique_together': {('product', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='irregularityrow',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='store.irregularitycategory'),
        ),
    ]
