# Generated by Django 5.2.5 on 2025-09-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_irregularityrow_product_irregularitycategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('group', models.CharField(choices=[('STRUCTURE', 'Structure'), ('FONCTION', 'Fonction')], default='STRUCTURE', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prelim_tables', to='store.product')),
            ],
            options={
                'verbose_name': "Table d'analyse préliminaire",
                'verbose_name_plural': "Tables d'analyse préliminaire",
                'ordering': ('order', 'title'),
                'unique_together': {('product', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PreliminaryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('irregularity', models.CharField(max_length=255, verbose_name='Irrégularité')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Référence')),
                ('actors', models.CharField(blank=True, max_length=255, verbose_name='Acteurs concernés')),
                ('dispositions', models.TextField(verbose_name='Dispositions pratiques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='store.preliminarytable')),
            ],
            options={
                'verbose_name': "Ligne d'analyse préliminaire",
                'verbose_name_plural': "Lignes d'analyse préliminaire",
                'ordering': ('order', 'id'),
            },
        ),
    ]
