# Generated by Django 5.2.5 on 2025-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_preliminarytable_preliminaryrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampleslide',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddField(
            model_name='exampleslide',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
