# Generated by Django 5.2.5 on 2025-09-27 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_payment_paymentevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(db_index=True, default="cinetpay", max_length=32)),
                (
                    "order_ref",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("signature", models.CharField(blank=True, default="", max_length=128)),
                ("raw_body", models.TextField(blank=True, default="")),
                ("processed", models.BooleanField(default=False)),
                ("http_status", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
