# Generated by Django 5.2.5 on 2025-09-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_paymentwebhooklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_fcfa",
            field=models.PositiveIntegerField(default=15000),
        ),
    ]
