# Generated by Django 5.2.5 on 2025-09-29 17:01

import uuid

from django.db import migrations


def fill_order_uuid(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    for obj in Order.objects.filter(uuid__isnull=True).iterator():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_add_order_uuid"),
    ]

    operations = [
        migrations.RunPython(fill_order_uuid, migrations.RunPython.noop),
    ]
