# Generated by Django 5.2.5 on 2025-10-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_order_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deliverable_file_6x9",
            field=models.FileField(
                blank=True,
                help_text="Version PDF format 6×9.",
                null=True,
                upload_to="deliverables/6x9/",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deliverable_file_a4",
            field=models.FileField(
                blank=True,
                help_text="Version PDF format A4.",
                null=True,
                upload_to="deliverables/a4/",
            ),
        ),
    ]
