# Generated by Django 4.2.16 on 2025-10-13 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_product_deliverable_file_6x9_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_slug", models.CharField(max_length=100)),
                ("order_ref", models.CharField(blank=True, max_length=120, null=True)),
                ("purchaser_email", models.EmailField(max_length=254)),
                ("purchaser_name", models.CharField(max_length=150)),
                ("delivery_email", models.EmailField(max_length=254)),
                ("service_role", models.CharField(max_length=150)),
                ("service_mission", models.TextField(blank=True)),
                ("uploaded_text", models.FileField(upload_to="bonus_texts/")),
                (
                    "proof_file",
                    models.FileField(
                        blank=True,
                        help_text="Preuve d’achat : PDF/PNG/JPG (optionnel si vous fournissez l’ID de commande).",
                        null=True,
                        upload_to="bonus_proofs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Reçue"),
                            ("DRAFTED", "Brouillon DOCX prêt"),
                            ("READY", "PDF prêt"),
                            ("SENT", "Envoyé"),
                            ("REJECTED", "Rejeté (non conforme)"),
                        ],
                        default="RECEIVED",
                        max_length=12,
                    ),
                ),
                (
                    "docx_path",
                    models.FileField(blank=True, null=True, upload_to="bonus_outputs/"),
                ),
                (
                    "pdf_path",
                    models.FileField(blank=True, null=True, upload_to="bonus_outputs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="bonusrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_ref__isnull", False)),
                fields=("product_slug", "order_ref", "purchaser_email"),
                name="uniq_bonusreq_with_orderref",
            ),
        ),
    ]
