# Generated by Django 5.2.5 on 2025-11-03 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_bonusrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinquiry",
            name="context_text",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="KitProcessingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("RUNNING", "En cours"),
                            ("DONE", "Terminé"),
                            ("FAILED", "Échec"),
                            ("PUBLISHED", "Publié"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("prompt_md", models.TextField(blank=True)),
                (
                    "word_file",
                    models.FileField(blank=True, null=True, upload_to="kit/word/"),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="kit/pdf/"),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="store.clientinquiry",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
