# Generated by Django 5.2.5 on 2025-11-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_clientinquiry_context_text_kitprocessingtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinquiry",
            name="ai_doc",
            field=models.FileField(
                blank=True,
                help_text="Document Word généré par IA",
                null=True,
                upload_to="kits/ai/",
            ),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="ai_done_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="ai_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "En attente"),
                    ("done", "Terminé"),
                    ("error", "Erreur"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="human_pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF final validé par humain",
                null=True,
                upload_to="kits/pdf/",
            ),
        ),
    ]
