# Generated by Django 5.2.5 on 2025-11-05 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_clientinquiry_ai_doc_clientinquiry_ai_done_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docx", models.FileField(upload_to="final/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_ready", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docx", models.FileField(upload_to="drafts/%Y/%m/")),
                ("built_at", models.DateTimeField(auto_now_add=True)),
                ("build_log", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("cinetpay", "CINETPAY"), ("om", "Orange Money")],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(help_text="Montant en XOF")),
                ("currency", models.CharField(default="XOF", max_length=8)),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="transaction_id/provider_ref",
                        max_length=120,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Créé"),
                            ("PENDING", "En attente"),
                            ("PAID", "Payé"),
                            ("FAILED", "Échoué"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("webhook_payload", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to="store.order",
            ),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Créé"),
                    ("PENDING", "En attente"),
                    ("PAID", "Payé"),
                    ("FAILED", "Échoué"),
                ],
                db_index=True,
                default="CREATED",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="processing_state",
            field=models.CharField(
                choices=[
                    ("INQUIRY_RECEIVED", "Demande reçue"),
                    ("PAID", "Payé"),
                    ("IA_RUNNING", "IA en cours"),
                    ("DRAFT_DONE", "Brouillon terminé"),
                    ("FINAL_UPLOADED", "Final uploadé"),
                    ("PUBLISHED", "Publié"),
                ],
                db_index=True,
                default="INQUIRY_RECEIVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_tokens",
                to="store.clientinquiry",
            ),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="max_uses",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clientinquiry",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="downloadtoken",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="downloadtoken",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_token",
                to="store.order",
            ),
        ),
        migrations.AlterField(
            model_name="downloadtoken",
            name="token",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="clientinquiry",
            index=models.Index(
                fields=["payment_status"], name="store_clien_payment_9cb418_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientinquiry",
            index=models.Index(
                fields=["processing_state"], name="store_clien_process_004aeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientinquiry",
            index=models.Index(fields=["email"], name="store_clien_email_9fc0fa_idx"),
        ),
        migrations.AddConstraint(
            model_name="downloadtoken",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("order__isnull", False),
                    ("inquiry__isnull", False),
                    _connector="OR",
                ),
                name="downloadtoken_order_or_inquiry_required",
            ),
        ),
        migrations.AddField(
            model_name="finalasset",
            name="inquiry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="final_asset",
                to="store.clientinquiry",
            ),
        ),
        migrations.AddField(
            model_name="finalasset",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_final_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generateddraft",
            name="inquiry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_draft",
                to="store.clientinquiry",
            ),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="inquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_intents",
                to="store.clientinquiry",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["external_ref"], name="store_payme_externa_0e44e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["status"], name="store_payme_status_3e9702_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["inquiry", "status"], name="store_payme_inquiry_2f912a_idx"
            ),
        ),
    ]
