# Generated by Django 4.2.26 on 2025-11-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_add_kit_complet_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinquiry",
            name="complexity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("simple", "Dossiers simples"),
                    ("standard", "Standard"),
                    ("complexe", "Complexes / sensibles"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="docs_count",
            field=models.PositiveIntegerField(
                default=1, help_text="Nombre de documents transmis / à traiter."
            ),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="estimated_price_fcfa",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Montant TTC estimé en FCFA au moment du devis.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="inquiry_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("QUOTED", "Devis généré"),
                    ("PAID", "Payé"),
                ],
                default="DRAFT",
                help_text="Statut de la demande de kit (distinct du status général).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clientinquiry",
            name="selected_tier_code",
            field=models.CharField(
                blank=True,
                help_text="Code interne du palier (essentiel_plus / complete_pro / expert_audit).",
                max_length=50,
            ),
        ),
    ]
