# Generated by Django 4.2.26 on 2025-12-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_add_orange_money_payment_models"),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinquiry',
            name='final_ai_document',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='kit_final_ai/',
                help_text='Document Word final uploadé (généré localement via Ollama + relecture)'
            ),
        ),
    ]
