# Generated by Django 4.2.26 on 2025-12-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_add_final_ai_document"),
    ]

    operations = [
        migrations.CreateModel(
            name='KitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, help_text='ID de suivi unique (ex: KCP-00001)', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Nom complet du client', max_length=200)),
                ('email', models.EmailField(help_text='Email du client', max_length=254)),
                ('offer', models.CharField(choices=[('ESSENTIEL_PLUS', 'Essentiel+'), ('COMPLET_PRO', 'Complet Pro'), ('EXPERT_AUDIT', 'Expert Audit')], help_text='Offre choisie', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Montant payé en FCFA', max_digits=10)),
                ('estimated_delay_hours', models.PositiveIntegerField(default=72, help_text='Délai estimé en heures ouvrables')),
                ('status', models.CharField(choices=[('PAYMENT_RECEIVED', 'Paiement reçu'), ('ANALYSIS', 'Analyse des documents'), ('WRITING', 'Rédaction en cours'), ('REVIEW', 'Relecture & consolidation'), ('DONE', 'Livraison finale')], db_index=True, default='PAYMENT_RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Date de livraison estimée ou confirmée', null=True)),
                ('starter_pack_delivered', models.BooleanField(default=False, help_text='Indique si le lien Starter Pack a été fourni')),
                ('inquiry', models.ForeignKey(blank=True, help_text='Lien vers la demande ClientInquiry originale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_orders', to='store.clientinquiry')),
                ('order', models.ForeignKey(blank=True, help_text="Lien vers l'Order de paiement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_orders', to='store.order')),
            ],
            options={
                'verbose_name': 'Commande Kit personnalisé',
                'verbose_name_plural': 'Commandes Kit personnalisé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kitorder',
            index=models.Index(fields=['tracking_id'], name='store_kitor_trackin_idx'),
        ),
        migrations.AddIndex(
            model_name='kitorder',
            index=models.Index(fields=['status', 'created_at'], name='store_kitor_status_idx'),
        ),
    ]
