[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
fixable = ["E", "F", "I"]

# Ignorer E501 dans migrations et seeds (texte long)
per-file-ignores = {
  "*/migrations/*.py" = ["E501"],
  "store/seeds/*.py" = ["E501"]
}

[tool.djlint]
profile = "django"
max_line_length = 100
format_css = true
format_js = true
