# Generated by Django 5.2.5 on 2025-09-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("mentions", "Mentions légales"),
                            ("privacy", "Politique de confidentialité"),
                            ("cookies", "Politique Cookies"),
                        ],
                        max_length=20,
                    ),
                ),
                ("html_content", models.TextField(help_text="Contenu HTML sûr (tu le maîtrises).")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Brouillon"), ("published", "Publié")],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document légal",
                "verbose_name_plural": "Documents légaux",
            },
        ),
    ]
