# Generated by Django 5.2.5 on 2025-09-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0004_alter_downloadcategory_required_sku_purchaseclaim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadcategory",
            name="is_protected",
        ),
        migrations.RemoveField(
            model_name="downloadcategory",
            name="required_sku",
        ),
    ]
