# Generated by Django 5.2.5 on 2025-09-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0005_remove_downloadcategory_is_protected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadcategory",
            name="is_protected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="downloadcategory",
            name="required_sku",
            field=models.CharField(
                blank=True, help_text="Code produit requis (ex: EBOOK_ASP)", max_length=64
            ),
        ),
    ]
