# Generated by Django 4.2.16 on 2025-10-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0008_secure_phase1_slugs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("selar", "Selar"),
                            ("publiseer", "Publiseer"),
                            ("youscribe", "YouScribe Afrique"),
                            ("chariow", "Chariow"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("order_ref", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "claim_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_entitlements",
                        to="downloads.downloadcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Droit d'accès externe",
                "verbose_name_plural": "Droits d'accès externes",
                "unique_together": {("email", "category", "platform", "order_ref")},
            },
        ),
    ]
