"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util
import os
from pathlib import Path

from dotenv import load_dotenv
from environs import Env

# Charger le fichier .env
load_dotenv()

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DB_SUFFIX = os.getenv("DB_SUFFIX", "dev")

# --- DEBUG & SECRET ---
DEBUG = os.getenv("DJANGO_DEBUG", "0") == "1"
SECRET_KEY = env("DJANGO_SECRET_KEY", default="dev-insecure-key")  # sûr pour tests *seulement*

# --- ALLOWED_HOSTS Go/No-Go ---
if not DEBUG:
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
else:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# --- Cookies secure en prod ---
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# --- Reverse proxy TLS (ex: cPanel/Reverse proxy) ---
if os.getenv("USE_SECURE_PROXY_SSL_HEADER", "0") == "1":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# --- CSRF_TRUSTED_ORIGINS pour domaines prod (optionnel) ---
CSRF_TRUSTED_ORIGINS = [
    "https://auditsanspeur.com",
    "https://www.auditsanspeur.com",
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "store",
    "downloads",
    "legal",
]

# Whitenoise/static config (idempotent, single source of truth)
USE_WHITENOISE = os.getenv("USE_WHITENOISE", "1").lower() not in ("0", "false", "off")
HAS_WHITENOISE = importlib.util.find_spec("whitenoise") is not None

MIDDLEWARE = ["django.middleware.security.SecurityMiddleware"]
if USE_WHITENOISE and HAS_WHITENOISE:
    MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")
MIDDLEWARE += [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
if USE_WHITENOISE and HAS_WHITENOISE:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
else:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / f"db_{DB_SUFFIX}.sqlite3",
    }
}

# (optionnel) log rapide du fichier DB en dev
if os.getenv("PRINT_DB_PATH") == "1":
    print(f"[settings] Using DB file: {DATABASES['default']['NAME']}")

AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Africa/Bamako"
USE_I18N = True
USE_TZ = True

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---- CinetPay: variables d'environnement ----
CINETPAY_SITE_ID = os.environ.get("CINETPAY_SITE_ID")
CINETPAY_API_KEY = os.environ.get("CINETPAY_API_KEY")
# Certaines intégrations fournissent un secret distinct. Laisse vide si non fourni.
CINETPAY_SECRET_KEY = os.environ.get("CINETPAY_SECRET_KEY")

# URLs de callback (dev par défaut, surchargées par l'environnement prod)
CINETPAY_NOTIFY_URL = os.environ.get(
    "CINETPAY_NOTIFY_URL", "http://127.0.0.1:8000/payments/cinetpay/notify/"
)
CINETPAY_RETURN_URL = os.environ.get(
    "CINETPAY_RETURN_URL", "http://127.0.0.1:8000/payments/cinetpay/return/"
)
CINETPAY_CANCEL_URL = os.environ.get(
    "CINETPAY_CANCEL_URL", "http://127.0.0.1:8000/payments/cinetpay/cancel/"
)

# Variables héritées (compatibilité)
CINETPAY_ENV = os.getenv("CINETPAY_ENV", "sandbox")
CINETPAY_BASE_URL = os.getenv("CINETPAY_BASE_URL", "https://api-checkout.cinetpay.com/v2/payment")

# # settings.py (dev)
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "mail.auditsanspeur.com"
# EMAIL_PORT = 465
# EMAIL_HOST_USER = "contact@auditsanspeur.com"
# # Assurez-vous de définir EMAIL_HOST_PASSWORD dans les variables d'environnement
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
# EMAIL_USE_SSL = True
# EMAIL_USE_TLS = False


# Email config
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "mail.auditsanspeur.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 465))
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "True") == "True"
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER